### ISSUE TITLE
Converting date format from ISOString to MySQL format

### ISSUE THREAD

**Issue by vtrofin** [vtrofin/takezo#10]
Is there a nicer way to convert the datetime from ISOString to the MySQL date format?  
My custom function looks like this: 
https://github.com/vtrofin/takezo/blob/afd59ef31f31ce97af9df04d40d8533aa4adee5e/ql/qlhelpers.js#L26-L44

**Comment by martinheidegger** [comment]
These are two issues, please close this issue and split into two.
