### ISSUE TITLE
GraphQL server - query returns result null

### ISSUE THREAD

**Issue by vtrofin** [vtrofin/takezo#7]
I am running this query 
```javascript
query {
  node (id: "users:2") {
  	... on User {
      id
      username
    }
  }
}
```
and the returned result is 
```javascript
{
  "data": {
    "node": null
  }
}
```

I've checked the NodeInterface implemented  here but I don't find anything wrong with it 
https://github.com/vtrofin/takezo/blob/9463632c5c14d6d88efa9afa504bfb5ce10e3d09/ql/types.js#L18-L37
Also checked that  helpers is initialized before using dbIdToNodeId function https://github.com/vtrofin/takezo/blob/9463632c5c14d6d88efa9afa504bfb5ce10e3d09/ql/types.js#L11-L16 
https://github.com/vtrofin/takezo/blob/9463632c5c14d6d88efa9afa504bfb5ce10e3d09/ql/qlhelpers.js#L1-L5
here is the root query https://github.com/vtrofin/takezo/blob/9463632c5c14d6d88efa9afa504bfb5ce10e3d09/server.js#L35-L62

and here is the response edited in the getNodeById function (function called by the root query resolver) . This should be the source argument passed to resolveType function in the  above NodeInterface

```javascript 
{ id: 2,
  username: 'gfd',
  nickname: null,
  email: 'gaviota',
  created_at: 2018-01-15T08:52:40.000Z,
  status: 'inactive',
  salt: 'df6141ae',
  encrypted_password: '9737690c1e487633809c6af02e721d75c5f082013c7852df9570d4c1ed9fc5409a86cb0f1de5a58cce26986805c34cf7b43509164dc137545d09e5cb0ba18741',
  avatar: null,
  __tableName: 'users' }
```

**Comment by vtrofin** [comment]
The only argument i can find as undefined is source in the RootQuery resolver, but i don't think it matters in this case. I just passed (source, args) just because it was specified like this in the example i follow. My understanding is that there is no source being passed since the query only has an argument (a node id in my case). 

```javascript
resolve(source, args) {
  console.log('===debug===')
  // console.log('db in resolver');
  // console.log(db);
  console.log('source ' + source);
  console.log('args ');
  console.log(args);
  console.log('---')
  return loaders.getNodeById(args.id, db)
}
```

My understanding is that the source passed to the NodeInterface resolverType is the returned value of the getNodeById function.. an object containing keys such as id, username  and so on.

I am not sure if I'm missing something obvious here.

**Comment by martinheidegger** [comment]
Closed I guess
