### ISSUE TITLE
getPostId function - return the number of posts existing before applying the filtering args and pass it down the promise chain

### ISSUE THREAD

**Issue by vtrofin** [vtrofin/takezo#9]
https://github.com/vtrofin/takezo/blob/e477ad403b2aa1981461e99e329af3e7a2e99884/ql/loaders.js#L53-L143

In the function above I just need to make the hasNextPage and hasPreviousPage from the graphQL pageinfo object. Currently hasNextPage and hasPreviousPage are always false because I apply the arguments to the query, thus the allRows variable has the filtered results (based on args) instead of all results. 
How can I save in a variable the number of results (unfiltered, befored passing in args such as first, after, etc) and pass it down the promise chain so that I can use it in the hasNextPage and hasPreviousPage functions? 

I am thinking at 2 options here:
1. save the total number of results returned from the db somewhere on row 61. I wasn't able to make this work (for the obvious reasons.. allRowsReturned contains the length of the filtered results when the promise is resolved )
```javascript
let query = db.select('*')
  .from('posts')
  .where('author_id', userSource.id)

const allRowsReturned = query
  .then(results => return results.length)
```
2. return the query will all results and then apply filters down the promise chain 
```javascript
		let query = db.select('*')						
			.from('posts')
			.where('author_id', userSource.id)

		return query
			.then((allRows) => {
				filter the array here 
```
What is the correct approach here? I am assuming i have to make option 1 work so I don't return a long list of results from the database. However I am stuck at how to get the number of results and passing it down to hasNextPage or hasPreviousPage function

**Comment by martinheidegger** [comment]
What you are asking is quite a tricky question, that fortunately has an easy solution, consider your query and query more:

1. **Consider your query**
     `after` only makes sense in combination with `first` and `before` only with `last`. So, lets focus on the `after` case first: If there is no `after` defined then obviously `hasPreviousPage() === false`. Same can be applied to `hasNextPage()`

2. **Query more**
      Say you have a page of 10 entries but you actually load 11 entries. If the result has only 10 entries then you know that there is no next page, if there are 11 entries you know if there is another page waiting after the current page.

**Comment by vtrofin** [comment]
I applied the above suggestions in the hasNextPage and hasPreviousPage functions. 
https://github.com/vtrofin/takezo/blob/e84bd493addcc538849710400c164eb78bb34d65/ql/loaders.js#L105-L115

Regarding hasPreviousPage(), how do you deal with the exception like the one below, when users insert cursors that do not point to items existing in the database? I can only think of making another query to the db and checking if the id and creation date are found in the database. Is there a better option for this?

In the example below I have only 4 posts in my db, but i wrongly return hasPreviousPage true.
```javascript
{
  node(id: "users:1") {
    ... on User {
      id
      posts(before: "10:2019-01-05T12:35:00.000Z") {
        pageInfo {
          hasNextPage
          hasPreviousPage
          startCursor
          endCursor
        }
        edges {
          cursor
          node {
            id
            title
          }
        }
      }
    }
  }
}
```
which returns hasPreviousPage: true
```javascript
{
  "data": {
    "node": {
      "id": "users:1",
      "posts": {
        "pageInfo": {
          "hasNextPage": false,
          "hasPreviousPage": true,
          "startCursor": "1:2018-01-02T12:35:00.000Z",
          "endCursor": "4:2018-01-05T12:35:00.000Z"
        },
        "edges": [
          {
            "cursor": "1:2018-01-02T12:35:00.000Z",
            "node": {
              "id": "posts:1",
              "title": "What is Lorem Ipsum?"
            }
          },
          {
            "cursor": "2:2018-01-03T12:35:00.000Z",
            "node": {
              "id": "posts:2",
              "title": "Where does it come from?"
            }
          },
          {
            "cursor": "3:2018-01-04T12:35:00.000Z",
            "node": {
              "id": "posts:3",
              "title": "Why do we use it?"
            }
          },
          {
            "cursor": "4:2018-01-05T12:35:00.000Z",
            "node": {
              "id": "posts:4",
              "title": "Where can I get some?"
            }
          }
        ]
      }
    }
  }
}
```
